name: C

on:
  push:
    paths:
      - '**/*.c'
      - '.github/workflows/c.yml'
      - 'test-c/**'
      - 'data/**'
      - 'Makefile'
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make test_all
      run: make test_all
